# Generated by Django 5.2.5 on 2025-08-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('year', 'month')},
            },
        ),
    ]
